### ISSUE TITLE
the code of IDUE-PS

### ISSUE THREAD

**Issue by programyy** [xiaolangu/ID-LDP#1]
Hello, Gu Xiaolan, I have a little question to ask you.
  I hope you can provide the code of IDUE-PS，because I want to quote your paper and implement this mechanism.But my code ability is limited, so I hope you can provide the source code.I would appreciate it if you could.
  Everything goes well for you.

**Comment by xiaolangu** [comment]
Hi! Thanks for your interests to our paper. I just added the code of `IDUE-PS` into a folder `item_set`, which is almost the same as `IDUE` but first runs `padding-and-sampling`.

**Comment by programyy** [comment]
a

**Comment by programyy** [comment]
Thank you very much for your timely reply and help. I hope you will have a good mood every day in the future!
